name: continuous-integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and run tests
        run: make
